### ISSUE TITLE
cant figure out how to switch from img>img to text>img

### ISSUE THREAD

**Issue by pixeldust-hash** [Ling-APE/ComfyUI-All-in-One-FluxDev-Workflow#1]
basically im an idiot. only a few days into comfyui so im still learning the ropes. trying to use prompt > img rather than img > img.

**Comment by Ling-APE** [comment]
![image](https://github.com/user-attachments/assets/4ce2cb54-1bb1-46d3-be06-7977b8c261fb)
Hi, It's controlled by this switch in the "Image to image or size selection" group.

**Comment by Gr4ph1xZ** [comment]
I tried this but i always get the ControlNet Preprocessing img after starting the workflow, no matter what i select at the image source switch
